#!/bin/bash
for i in `find . -name *.mkv -print|grep -v encoded`; do 
	mkdir -p ~/Videos/encoded/$i \
	&& ffmpeg -i $i -acodec copy \
	-vcodec libx264 \
	-scodec copy \
	~/Videos/encoded/$i.mkv \
	&& rmdir ~/Videos/encoded/$i \
	&& rename ".mkv.mkv" ".mkv" ~/Videos/encoded \
	&& rm -rf $i
done
exit 0
#-t 500 \
#-vcodec libx265 -preset slower -crf 20.0 -qcomp 0.8 \
#-vcodec libx265 -preset ultrafast \
#-vcodec libx265 -preset slower -ctu 32 -max-tu-size 16 -crf 20.0 -tu-intra-depth 2 -tu-inter-depth 2 -rdpenalty 2 -me 3 -subme 5 -merange 44 -b-intra -no-amp -ref 5 -weightb -keyint 360 -min-keyint 1 -bframes 8 -aq-mode 1 -aq-strength 1.0 -rd 5 -psy-rd 1.5 -psy-rdoq 5.0 -rdoq-level 1 -no-sao -no-open-gop -rc-lookahead 80 -scenecut 40 -max-merge 4 -qcomp 0.8 -no-strong-intra-smoothing -deblock -2:-2 -qg-size 16 -pbratio 1.2 \
